#!/bin/bash

# Kill any old instances to prevent conflicts
pkill -f groq-dictate.py

# Set Groq API Key
set -a
source $HOME/.secrets
set +a

# Set Groq Directory
export GROQDIR=/var/home/eric/src/github.com/dcoffline/groq-dictate

# Set Audio Path
export XDG_RUNTIME_DIR=/run/user/$(id -u)

# Bridge for Homebrew Audio
export ALSA_PLUGIN_DIR=/usr/lib64/alsa-lib

# Display config
export WAYLAND_DISPLAY=wayland-0

# Log for debugging
exec >$GROQDIR/groq_debug.log 2>&1

# Run it
$GROQDIR/.venv/bin/python $GROQDIR/groq-dictate.py
